version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: zbx-postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zbx-server
    depends_on:
      - db
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      # Parâmetros opcionais abaixo
      # ZBX_STARTPOLLERS: "5"
      # ZBX_STARTPOLLERS_UNREACHABLE: "1"
    volumes:
      - zbx_server_conf:/etc/zabbix/zabbix_server.conf
    ports:
      - "10051:10051"  # Porta do Zabbix Server
    restart: unless-stopped

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zbx-web
    depends_on:
      - db
      - zabbix-server
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo  # Ajuste para seu timezone
      # Parâmetros opcionais
      # PHP_VALUE_MEMORY_LIMIT: 256M
      # PHP_VALUE_MAX_EXECUTION_TIME: 300
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - zbx_web_conf:/etc/zabbix/
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zbx-agent
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_ACTIVE_SERVER: zabbix-server
    restart: unless-stopped

volumes:
  pgdata:
  zbx_server_conf:
  zbx_web_conf:
